version: '3.8'

networks:
  tig:

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file: env/influxdb.env
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - tig
    volumes:
      - ./data/influxdb:/var/lib/influxdb:rw

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: env/grafana.env
    user: 0:0
    ports:
      - 80:3000
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
    networks:
      - tig
    restart: always
